### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luandro** [klutchell/balena-nginx-proxy-manager#2]
Getting this error with the proxy:
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by klutchell** [comment]
What type of device are you using? I believe it only works with Raspberry Pi 4 or a similar x64 device.

**Comment by hiurequeiroz** [comment]
I try Raspberry Pi 4 and got the same error

`[Build]   proxy   Step 4/7 : RUN patch -u /etc/nginx/nginx.conf -i /app/nginx.conf.patch
[Build]   db       ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
[Build]   db       ---> Running in a13927265707
[Build]   db      standard_init_linux.go:219: exec user process caused: exec format error
[Build]   sqldump  ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
[Build]   sqldump  ---> Running in fafb340ab13f
[Build]   sqldump standard_init_linux.go:219: exec user process caused: exec format error
[Build]   proxy    ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
[Build]   proxy    ---> Running in 6ba4c2fbb468
[Build]   proxy   standard_init_linux.go:219: exec user process caused: exec format error
[Build]   Built 3 services in 0:05
[Error]   Deploy failed
The command '/bin/sh -c patch -u /etc/nginx/nginx.conf -i /app/nginx.conf.patch' returned a non-zero code: 1

and whit debug option

Error: The command '/bin/sh -c patch -u /etc/nginx/nginx.conf -i /app/nginx.conf.patch' returned a non-zero code: 1
    at Stream.<anonymous> (/snapshot/versioned-source/node_modules/resin-docker-build/build/builder.js:181:23)
    at Stream.stream.write (/snapshot/versioned-source/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:198:13)
    at Stream.EventEmitter.emit (domain.js:448:20)
    at drain (/snapshot/versioned-source/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/snapshot/versioned-source/node_modules/through/index.js:45:5)
    at Parser.exports.parse.parser.onToken (/snapshot/versioned-source/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/snapshot/versioned-source/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/snapshot/versioned-source/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/snapshot/versioned-source/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:710:20)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
From previous event:
    at createBuildStream.Bluebird.try.then (/snapshot/versioned-source/node_modules/resin-docker-build/build/builder.js:73:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Builder.createBuildStream (/snapshot/versioned-source/node_modules/resin-docker-build/build/builder.js:72:97)
    at taskResolved.then (/snapshot/versioned-source/node_modules/resin-multibuild/build/build.js:89:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by klutchell** [comment]
Are you using the balena CLI for build or push? What command is outputting this result?

**Comment by hiurequeiroz** [comment]
I just use the deploy command.
I change the docker-compose https://gitlab.com/coletivo-coolab/jurebaba/-/blob/main/docker-compose.yml
and comment the line `RUN patch -u /etc/nginx/nginx.conf -i /app/nginx.conf.patch` in dockefile in the proxy folder. I did and then it worked

**Comment by klutchell** [comment]
What device type is this running on though? I didn't mean to build/deploy it from the Raspberry Pi 4.

You need to use the `emulated` flag to build/deploy ARM images from your x86 workstation to an ARM device.

https://www.balena.io/docs/reference/balena-cli/#-e---emulated-1

`exec format error` usually means you are attempting to run an x86 image on ARM, or the other way around.

**Comment by hiurequeiroz** [comment]
Yes, its work fine!
thank you for your help
